name: Deploy to Fauzi Server

on:
  # trigger the workflow when release is created
  release:
    types: [published]


jobs:
  deploy:
    name: Build and Deploy to Fauzi Server
    runs-on: ubuntu-latest

    # checkout to the commit hash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build Astro App
      run: npm run build

    # - name: Deploy to Fauzi Server
    #   uses: easingthemes/ssh-deploy@main
    #   with:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     SOURCE: "dist/"
    #     TARGET: "/var/www/html/astro"